schema_version: 1

context:
  name: basedmypy
  version: 2.9.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/basedmypy-${{ version }}.tar.gz
  sha256: 4a0ae51d77ed30f3d653addebc61d39a4414db7852f01bd4a3d741a1ffe2a8a0

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - mypy=mypy.__main__:console_entry
      - stubgen=mypy.stubgen:main
      - stubtest=mypy.stubtest:main
      - dmypy=mypy.dmypy.client:console_entry
      - mypyc=mypyc.__main__:main

requirements:
  host:
    - python ${{ python_min }}
    - setuptools >=40.6.2
    - wheel >=0.30.0
    - basedtyping >=0.0.3
    - typing_extensions >=4.1.0
    - mypy_extensions >=1.0.0
    - tomli >=1.1.0
    - types-psutil
    - types-setuptools
    - pip
  run:
    - python >=${{ python_min }}
    - basedtyping >=0.0.3
    - typing-extensions >=4.1.0
    - mypy_extensions >=1.0.0
    - tomli >=1.1.0

tests:
  - python:
      imports:
        - mypy
  - requirements:
      run:
        - python ${{ python_min }}
        - pip
    script:
      - pip check
      - mypy --help
      - stubgen --help
      - stubtest --help
      - dmypy --help
      - mypy --version

about:
  summary: Based static typing for Python
  license: BSD-3-Clause AND Apache-2.0
  license_file:
    - LICENSE
    - mypyc/external/googletest/LICENSE
    - mypy/typeshed/LICENSE
  homepage: https://github.com/KotlinIsland/basedmypy

extra:
  recipe-maintainers:
    - rxm7706
    - lucascolley
